services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    volumes:
      - ./services/api:/var/www
    working_dir: /var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      - db
    ports:
      - "8000:8000"

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    volumes:
      - ./services/web:/app
    working_dir: /app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  dbdata: