services:
  db:
    image: mysql:8.0
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  laravel:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./services/api:/var/www
      - /var/www/vendor
      - /var/www/storage
      - /var/www/bootstrap/cache
    working_dir: /var/www
    depends_on:
      - minio
      - minio-client
      - db


  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./services/api:/var/www
      - ./services/api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel

  minio:
    image: minio/minio:latest
    env_file: .env
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  minio-client:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set myminio http://minio:9000 minio minio123 &&
      mc mb -p myminio/photos || true &&
      mc anonymous set download myminio/photos
      "

  nextjs:
    build:
      context: ./services/web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file: .env
    volumes:
    - ./services/web:/app
    - /app/node_modules
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - laravel

volumes:
  db-data:
  minio-data: