import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../css/globals.css";
import { Provider } from "@/components/ui/provider"
import Header from "@/components/layout/Header";
import {Container, Flex} from "@chakra-ui/react";
import { Toaster } from "@/components/ui/toaster"
import React from "react";
import ScrollTopButton from "@/components/ui/ScrollTopButton";

const montserrat = Montserrat({
    subsets: ["latin"],
    weight: ["300", "500", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body className={montserrat.className}>
        <Provider>
            <ScrollTopButton/>
            <Toaster />
            <Header/>
            <Flex mt={6} justify="center" className="h-100">
                <Container maxW="6xl" className="h-100" py="12" px="6">
                    {children}
                </Container>
            </Flex>

        </Provider>
      </body>
    </html>
  );
}
